### ISSUE TITLE
A basic question ;)

### ISSUE THREAD

**Issue by fplanque** [omarkhorshid/OpenRad#1]
As you can measure it, allow me to ask:

- Can the radioactivity of your sources go through a wall?
- Through a plank of wood?
- Through a sheet of paper?

Thanks.

**Comment by omarkhorshid** [comment]
Well, the ability of radiation to penetrate materials depends on the type of radiation:

- **Alpha particles**: Consist of 2 protons and two neutrons making it identical to helium-4 nucleus. They are the least penetrating and can be stopped by a sheet of paper or even a few centimeters of air. They cannot go through a wall or a plank of wood.
  
- **Beta particles**: Are high speed electrons or positrons and have greater penetrating power than alpha particles but can still be blocked by a few millimeters of plastic, glass, or a thin sheet of metal. They can penetrate paper but are unlikely to pass through a wall or a thick plank of wood.
  
- **Gamma rays** and **X-rays** Are photons of electromagnetic energy and have the highest penetration power. They can pass through paper, wood, and even some walls, depending on the wall's thickness and material. Dense materials like lead or several centimeters of concrete are typically used to block gamma rays. That's why they are used in radiography.

The source used to test this project is Americium-241 which is a strong alpha emitter and emitts a bit of gamma as well. The tube used in the project (SBM-20) has a copper body which stops all of the alpha particles and prevent detection of such radiation. However gamma rays and hard beta particles (high energy beta) can be detected with the tube.
That's why if I put a piece of paper , a plank of wood or even a wall (a thin enough wall to not attenuate the radiation due to distance) between the device and the source, I'd still be able to pick up elevated levels of radiation using the device.

I hope this answers your question.

**Comment by fplanque** [comment]
Thank you for the detailed and very interesting answer! 👍

**Comment by omarkhorshid** [comment]
Adding the following diagram for demonstration.
![RDT_20241122_1511375746892206943729382.jpg](https://github.com/user-attachments/assets/68f7cfec-7cb5-4d7b-bd83-639ad6aae39e)
